-- L'Atlas des Esprits : les mondes deviennent les sept régions de la vision, chacune avec son
-- paysage (thème), dans l'ordre Jardin, Bibliothèque, Atelier, Observatoire, Conservatoire,
-- Forêt, Sommet. Écrit par scripts/atlas-migration.ts. Sans effet sur une base vide : le seed
-- crée alors directement les régions.

-- Anciennes palettes vers les régions (mondes créés dans l'éditeur compris).
UPDATE "World" SET "theme" = CASE "theme" WHEN 'origines' THEN 'jardin' WHEN 'ocean' THEN 'observatoire' WHEN 'cosmos' THEN 'sommet' ELSE "theme" END;

UPDATE "World" SET "slug" = 'jardin-des-echos', "title" = 'Le Jardin des Échos', "tagline" = 'Observer, c''est déjà relier.', "description" = 'Première page de l''Atlas des Esprits. Ici, les choses ne sont pas seulement posées les unes à côté des autres : elles se répondent. Observe-les, et elles vont par deux.', "theme" = 'jardin', "order" = 0, "updatedAt" = now() WHERE "slug" = 'origines';
UPDATE "World" SET "slug" = 'bibliotheque-vivante', "title" = 'La Bibliothèque Vivante', "tagline" = 'Les livres se souviennent de ce qu''on leur confie.', "theme" = 'bibliotheque', "order" = 1, "updatedAt" = now() WHERE "slug" = 'bibliotheque-vivante';
UPDATE "World" SET "slug" = 'atelier-des-inventeurs', "title" = 'L''Atelier des Inventeurs', "tagline" = 'Chaque rouage attend sa juste place.', "theme" = 'atelier', "order" = 2, "updatedAt" = now() WHERE "slug" = 'atelier-des-inventeurs';
UPDATE "World" SET "slug" = 'observatoire', "title" = 'L''Observatoire', "tagline" = 'Chaque étoile cherche sa jumelle.', "description" = 'Sous la coupole, le ciel s''est éteint. Relie chaque paire d''étoiles de même signe sans croiser les autres tracés, et fais passer la lumière par chaque case : le ciel entier doit briller.', "theme" = 'observatoire', "order" = 3, "updatedAt" = now() WHERE "slug" = 'canaux-d-ether';
UPDATE "World" SET "slug" = 'conservatoire', "title" = 'Le Conservatoire', "tagline" = 'Chaque note appelle la suivante.', "description" = 'Dans le Conservatoire, tout suit une mesure : les saisons, les heures, les phases de la lune. Retrouve l''ordre juste, du premier temps au dernier, et la musique reprend.', "theme" = 'conservatoire', "order" = 4, "updatedAt" = now() WHERE "slug" = 'rivage-des-suites';
UPDATE "World" SET "slug" = 'foret-des-connexions', "title" = 'La Forêt des Connexions', "tagline" = 'Ici, rien ne va seul : tout va par familles.', "theme" = 'foret', "order" = 5, "updatedAt" = now() WHERE "slug" = 'foret-des-echos';
UPDATE "World" SET "slug" = 'sommet-des-sages', "title" = 'Le Sommet des Sages', "tagline" = 'Toutes les facultés se rejoignent.', "description" = 'Au sommet de l''Atlas, les esprits se rassemblent. Devine la règle cachée des échos, puis retrouve en chemin tout ce que tu as appris : la mémoire, la logique et le regard qui embrasse l''espace.', "theme" = 'sommet', "order" = 6, "updatedAt" = now() WHERE "slug" = 'salle-des-echos';
UPDATE "World" SET "slug" = 'quotidien', "title" = 'Énigmes du jour', "tagline" = 'Une énigme par jour, la même pour tout le monde.', "theme" = 'sommet', "order" = 7, "updatedAt" = now() WHERE "slug" = 'quotidien';

-- L'Observatoire : les énigmes de Flux prennent des noms d'astres.
UPDATE "Level" SET "title" = 'Première lueur', "description" = 'Deux tracés, un petit coin de ciel.', "updatedAt" = now() WHERE "title" = 'La source' AND "worldId" = (SELECT "id" FROM "World" WHERE "slug" = 'observatoire');
UPDATE "Level" SET "title" = 'Les astres jumeaux', "description" = 'Les chemins se partagent l''espace.', "updatedAt" = now() WHERE "title" = 'Les rigoles' AND "worldId" = (SELECT "id" FROM "World" WHERE "slug" = 'observatoire');
UPDATE "Level" SET "title" = 'La lunette', "description" = 'Plus de tracés, plus de détours.', "updatedAt" = now() WHERE "title" = 'Le lavoir' AND "worldId" = (SELECT "id" FROM "World" WHERE "slug" = 'observatoire');
UPDATE "Level" SET "title" = 'Les orbites', "description" = 'Un grand ciel à éclairer.', "updatedAt" = now() WHERE "title" = 'Les aqueducs' AND "worldId" = (SELECT "id" FROM "World" WHERE "slug" = 'observatoire');
UPDATE "Level" SET "title" = 'La voie lactée', "description" = 'Les tracés s''entrelacent.', "updatedAt" = now() WHERE "title" = 'Le delta' AND "worldId" = (SELECT "id" FROM "World" WHERE "slug" = 'observatoire');
UPDATE "Level" SET "title" = 'La carte du ciel', "description" = 'Tout le ciel, d''un seul tenant.', "updatedAt" = now() WHERE "title" = 'La mer d''éther' AND "worldId" = (SELECT "id" FROM "World" WHERE "slug" = 'observatoire');

-- Le Sommet des Sages réunit les facultés : trois énigmes s'intercalent entre ses Échos.
UPDATE "Level" SET "order" = "order" * 2 WHERE "worldId" = (SELECT "id" FROM "World" WHERE "slug" = 'sommet-des-sages');
INSERT INTO "Level" ("id", "worldId", "order", "title", "description", "hints", "symbols", "columns", "mechanic", "puzzle", "kind", "groups", "published", "updatedAt")
SELECT 'atlas-sommet-1', w."id", 1, 'La mémoire des sages', 'Tout ce que l''esprit a appris à retenir, réuni sur une seule étagère.', ARRAY['Associe chaque symbole à sa rangée, puis à sa colonne.', 'Raconte-toi une petite histoire qui relie les symboles dans l''ordre.'], ARRAY[]::text[], 4, 'MEMORY'::"Mechanic",
       '{"columns":5,"cells":["💧","🦋",null,"🌱","📜","🪨",null,"⭐","🐚","☾",null,"🪶","🍂","❄","✦","🌸","🌊","🗝","🕯","☀"],"targets":[19,8,7,11,0,3,15],"progressive":true}'::jsonb, 'PAIRS'::"LevelKind", '[]'::jsonb, true, now()
FROM "World" w WHERE w."slug" = 'sommet-des-sages' AND NOT EXISTS (SELECT 1 FROM "Level" WHERE "id" = 'atlas-sommet-1');
INSERT INTO "Level" ("id", "worldId", "order", "title", "description", "hints", "symbols", "columns", "mechanic", "puzzle", "kind", "groups", "published", "updatedAt")
SELECT 'atlas-sommet-2', w."id", 3, 'Le mécanisme ancien', 'La plus vieille machine de l''Atlas attend que sa lumière revienne.', ARRAY['Pars de la source : chaque conduit doit mener quelque part.', 'Les coins et les bords ne laissent que peu d''orientations possibles.'], ARRAY[]::text[], 4, 'GEARS'::"Mechanic",
       '{"columns":7,"rows":7,"tiles":[{"mask":2,"rotation":0},{"mask":10,"rotation":2},{"mask":10,"rotation":1},{"mask":10,"rotation":3},{"mask":10,"rotation":3},{"mask":10,"rotation":2},{"mask":12,"rotation":0},{"mask":6,"rotation":2},{"mask":10,"rotation":0},{"mask":10,"rotation":2},{"mask":10,"rotation":1},{"mask":10,"rotation":2},{"mask":10,"rotation":1},{"mask":13,"rotation":0,"fixed":true},{"mask":5,"rotation":3},{"mask":2,"rotation":0},{"mask":10,"rotation":1},{"mask":12,"rotation":2},{"mask":6,"rotation":0},{"mask":10,"rotation":3},{"mask":9,"rotation":3},{"mask":7,"rotation":1},{"mask":10,"rotation":3},{"mask":12,"rotation":3},{"mask":3,"rotation":2},{"mask":9,"rotation":3},{"mask":6,"rotation":0},{"mask":12,"rotation":0},{"mask":5,"rotation":3},{"mask":6,"rotation":2},{"mask":9,"rotation":3},{"mask":6,"rotation":2},{"mask":10,"rotation":3},{"mask":9,"rotation":3},{"mask":5,"rotation":0},{"mask":5,"rotation":1},{"mask":5,"rotation":3},{"mask":6,"rotation":2},{"mask":9,"rotation":2},{"mask":4,"rotation":1},{"mask":6,"rotation":0},{"mask":13,"rotation":0},{"mask":1,"rotation":2},{"mask":3,"rotation":1},{"mask":11,"rotation":3},{"mask":10,"rotation":0},{"mask":9,"rotation":3},{"mask":1,"rotation":3},{"mask":1,"rotation":2}],"source":13}'::jsonb, 'PAIRS'::"LevelKind", '[]'::jsonb, true, now()
FROM "World" w WHERE w."slug" = 'sommet-des-sages' AND NOT EXISTS (SELECT 1 FROM "Level" WHERE "id" = 'atlas-sommet-2');
INSERT INTO "Level" ("id", "worldId", "order", "title", "description", "hints", "symbols", "columns", "mechanic", "puzzle", "kind", "groups", "published", "updatedAt")
SELECT 'atlas-sommet-3', w."id", 5, 'Les chemins du ciel', 'Vu d''en haut, le ciel entier est une carte à relier.', ARRAY['Commence par les tracés dont les étoiles sont proches.', 'Le long des bords, il n''y a souvent qu''un seul chemin possible.'], ARRAY[]::text[], 4, 'FLOW'::"Mechanic",
       '{"columns":8,"rows":8,"fill":true,"endpoints":[{"a":57,"b":28},{"a":20,"b":19},{"a":27,"b":44},{"a":45,"b":42},{"a":34,"b":16},{"a":8,"b":30}],"solution":[[57,56,48,40,41,49,50,58,59,60,61,62,63,55,47,39,38,37,29,28],[20,21,13,12,11,19],[27,35,36,44],[45,46,54,53,52,51,43,42],[34,33,32,24,16],[8,0,1,9,17,25,26,18,10,2,3,4,5,6,7,15,14,22,23,31,30]]}'::jsonb, 'PAIRS'::"LevelKind", '[]'::jsonb, true, now()
FROM "World" w WHERE w."slug" = 'sommet-des-sages' AND NOT EXISTS (SELECT 1 FROM "Level" WHERE "id" = 'atlas-sommet-3');
